version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    android-dependencies:
      patterns:
        - "Xamarin.*"
    unittest-dependencies:
      patterns:
        - "xunit"
        - "xunit.*"
        - "XunitXml.*"
        - "Microsoft.NET.Test*"
        - "dotnet-reportgenerator-globaltool"
        - "Microsoft.Testing.Extensions.*"
        - "NSubstitute"
        - "NSubstitute.*"
    analyzers:
      patterns:
        - "AsyncFixer"
        - "*Analyzer*"
        - "Roslynator.*"
        - "SonarAnalyzer.*"
    logging:
      patterns:
        - "*.Extensions.Logging.*"
        - "Serilog.*"
        - "Serilog"
    
    build-tools:
      patterns:
        - "Cake.*"
        - "Microsoft.Windows.SDK.BuildTools"
        - "Microsoft.WindowsAppSDK"
