// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics.CodeAnalysis;
using MvvmCross.Platforms.Mac.Presenters.Attributes;
using MvvmCross.Platforms.Mac.Views;
using ObjCRuntime;
using Playground.Core.ViewModels;

namespace Playground.Mac
{
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
    public class ModalWindowController : MvxWindowController
    {
        public ModalWindowController(NativeHandle handle) : base(handle)
        {
        }

        public ModalWindowController(NSWindow window) : base(window)
        {
        }

        [Export("initWithCoder:")]
        public ModalWindowController(NSCoder coder) : base(coder)
        {
        }

        public ModalWindowController(string viewName, NSBundle bundle) : base(viewName, bundle)
        {
        }

        public ModalWindowController(string viewName) : base(viewName)
        {
        }

        public ModalWindowController()
        {
        }

        public override void ShowWindow(NSObject sender)
        {
            base.ShowWindow(sender);
            Window.WillClose += WindowOnWillClose;
            NSApplication.SharedApplication.RunModalForWindow(Window);
        }

        private void WindowOnWillClose(object sender, EventArgs e)
        {
            Window.WillClose -= WindowOnWillClose;
            NSApplication.SharedApplication.StopModal();
        }
    }

    [MvxFromStoryboard("Main")]
    [MvxModalPresentation]
    //[MvxWindowPresentation(WindowControllerName = "Playground.Mac.ModalWindowController, Playground.Mac")]
    //[MvxWindowPresentation(WindowControllerType = typeof(ModalWindowController))]
    public partial class ModalView : MvxViewController<ModalViewModel>
    {
        public ModalView(NativeHandle handle) : base(handle)
        {
            Title = "Modal view";
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = CreateBindingSet();
            set.Bind(btnClose).To(vm => vm.CloseCommand);
            set.Bind(btnShowModal).To(vm => vm.ShowNestedModalCommand);
            set.Bind(lblCount).To(vm => vm.Count);
            set.Apply();
        }
    }
}
