// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;

namespace DevDemo.Mac
{
	public partial class ColorCollectionViewItemController : NSViewController
	{
		public ColorCollectionViewItemController (IntPtr handle) : base (handle)
		{
		}
	}
}
