//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSellers.Droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int dialog_BoolField = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int dialog_Button = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int dialog_DisclosureField = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int dialog_ImageLeft = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int dialog_ImageRight = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int dialog_LabelField = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int dialog_LabelSubtextField = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int dialog_Panel = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int dialog_RadioButtonList = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int dialog_SliderField = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int dialog_Spinner = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int dialog_ValueField = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int iFormFieldValue = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int text1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int text2 = 2131034126;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_boolfieldleft = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldright = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldsubleft = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubright = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_button = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_datefield = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_fieldsetlabel = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_floatimage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_labelfieldbelow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_labelfieldright = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_onofffieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_panel = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_root = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_selectlist = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_selectlistfield = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_textarea = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_textfieldbelow = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_textfieldright = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ListItem = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Splash = 2130903059;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
