name: Feature Request
description: Suggest an idea for MvvmCross
labels: ["t/enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in MvvmCross! We welcome any and all ideas for features or improvements that you might have. All we ask is to fill in this template with some detail. A detailed description, perhaps supported with some screenshots, mockups, and a (public) API design in pseudo-code, would be very much appreciated and will help get your proposal reviewed sooner.
        
        Keep in mind that MvvmCross is a multi-platform framework. Consider how feasible it is to implement this feature across all the supported platforms.
        
        If you're not completely sure about a request yet, feel free to [open a discussion](https://github.com/MvvmCross/MvvmCross/discussions/categories/ideas) first to discuss with the team and the community first.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give us a detailed description of the feature that you envision. Focus on _what_ this feature does, over the _why_ you want this feature. What would be the end-result when implemented? Feel free to add any diagrams, (mocked up) screenshots, or other materials that support your story.
      placeholder: I would love to have...
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Intended Use-Case
      description: Provide a detailed example of where your proposal would be used and for what purpose. Focus on _why_ you want this feature instead of _what_ the feature does.
      placeholder: In my app I have a situation where I would really want a shiny button to make it stand out from the rest of the plain and boring buttons.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        By opening the issue you agree to follow this project's [Code of Conduct](https://github.com/MvvmCross/MvvmCross/blob/develop/CODE_OF_CONDUCT.md)