require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "MvvmCross-3.0.12.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="MvvmCross" \
		--summary="Add a huge amount of awesomeness to your Xamarin apps." \
		--publisher="MvvmCross" \
		--website="http://mvvmcross.wordpress.com/" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/MvvmCross_128x128.png" \
		--library="mobile":"../bin/Release/Mvx/Portable/Cirrious.CrossCore.dll" \
		--library="mobile":"../bin/Release/Mvx/Portable/Cirrious.MvvmCross.dll" \
		--library="mobile":"../bin/Release/Mvx/Portable/Cirrious.MvvmCross.Binding.dll" \
		--library="mobile":"../bin/Release/Mvx/Portable/Cirrious.MvvmCross.Localization.dll" \
		--library="iOS":"../bin/Release/Mvx/Touch/Cirrious.CrossCore.Touch.dll" \
		--library="iOS":"../bin/Release/Mvx/Touch/Cirrious.MvvmCross.Touch.dll" \
		--library="iOS":"../bin/Release/Mvx/Touch/Cirrious.MvvmCross.Binding.Touch.dll" \
		--library="android":"../bin/Release/Mvx/Droid/Cirrious.CrossCore.Droid.dll" \
		--library="android":"../bin/Release/Mvx/Droid/Cirrious.MvvmCross.Droid.dll" \
		--library="android":"../bin/Release/Mvx/Droid/Cirrious.MvvmCross.Binding.Droid.dll" \
		--sample="Sample. Demonstrates MvvmCross.":"samples/MvvmCross.Sample.sln"
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
