<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(_MvxWindowsTargets)</TargetFrameworks>
    <AssemblyName>MvvmCross.Platforms.WinUI</AssemblyName>
    <RootNamespace>MvvmCross.Platforms.WinUI</RootNamespace>
    <Description>MvvmCross is the .NET MVVM framework for cross-platform solutions, including Xamarin iOS, Xamarin Android, Xamarin Forms, Windows and Mac.

This package contains the 'MvvmCross.Platforms.WinUI' libraries for MvvmCross</Description>
    <PackageId>MvvmCross.Platforms.WinUI</PackageId>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <PropertyGroup>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MvvmCross</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\MvvmCross\readme.txt" pack="true" PackagePath="." />

    <Compile Include="..\MvvmCross\Platforms\WinUi\**\*.cs" />
    <Page Include="..\MvvmCross\Platforms\WinUi\**\*.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <None Update="**\*.xaml.cs" DependentUpon="%(Filename)" />
    <Compile Update="**\*.xaml.cs" DependentUpon="%(Filename)" />

    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />

    <ProjectReference Include="..\MvvmCross\MvvmCross.csproj" />
  </ItemGroup>

</Project>
