#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BestSellers.Droid.Resource", IsApplication=true)]

namespace BestSellers.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int MvxDropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int MvxItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int MvxSource = 2130771972;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int BookImageView = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int ErrorImage = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ErrorText1 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ErrorText2 = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int text1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int text2 = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int text3 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int text4 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int toast_layout_error_root = 2130968582;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem_Book = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListItem_Category = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page_BookListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page_BookView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Page_CategoryListView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ToastLayout_Error = 2130903047;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxImageView = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
