// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Mac.Views;
using Playground.Core.ViewModels;
using MvvmCross.Mac.Views.Presenters.Attributes;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    [MvxChildPresentation]
    public partial class ChildView : MvxViewController<ChildViewModel>
    {
        public ChildView(IntPtr handle) : base(handle)
        {
            Title = "Child view";
        }
    }
}
