// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Mac.Views;
using Playground.Core.ViewModels;
using MvvmCross.Mac.Views.Presenters.Attributes;
using MvvmCross.Binding.BindingContext;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    [MvxContentPresentation]
    public partial class ChildView : MvxViewController<ChildViewModel>
    {
        public ChildView(IntPtr handle) : base(handle)
        {
            Title = "Child view";
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = this.CreateBindingSet<ChildView, ChildViewModel>();
            set.Bind(btnRoot).To(vm => vm.ShowRootCommand);
            set.Apply();
        }
    }
}
