// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Playground.Core.ViewModels;
using MvvmCross.Mac.Views;
using MvvmCross.Mac.Views.Presenters.Attributes;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    [MvxChildPresentation]
    public partial class RootViewController : MvxViewController<RootViewModel>
    {
        public RootViewController() : base()
        {

        }

        public RootViewController(IntPtr handle) : base(handle)
        {
        }

        public override void LoadView()
        {
            base.LoadView();

            View = new NSView();
        }
    }
}
