// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Mac.Views;
using MvvmCross.Mac.Views.Presenters.Attributes;
using Playground.Core.ViewModels;
using MvvmCross.Binding.BindingContext;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    [MvxChildPresentation]
    public partial class RootView : MvxViewController<RootViewModel>
    {
        public bool MyValue { get; set; } = true;

        public RootView(IntPtr handle) : base(handle)
        {
            Title = "Root view";
        }

        public override void LoadView()
        {
            base.LoadView();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = this.CreateBindingSet<RootView, RootViewModel>();
            set.Bind(btnChild).To(vm => vm.ShowChildCommand);
            set.Bind(btnModal).To(vm => vm.ShowModalCommand);
            set.Apply();
        }
    }
}
