// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Mac.Views;
using Playground.Core.ViewModels;
using MvvmCross.Mac.Views.Presenters.Attributes;
using MvvmCross.Binding.BindingContext;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    [MvxSheetPresentation]
    public partial class SheetView : MvxViewController<SheetViewModel>
    {
        public SheetView(IntPtr handle) : base(handle)
        {
            Title = "Sheet view";
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = this.CreateBindingSet<SheetView, SheetViewModel>();
            set.Bind(btnClose).To(vm => vm.CloseCommand);
            set.Apply();
        }
    }
}
