// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Mac.Views.Presenters.Attributes;
using MvvmCross.Mac.Views;
using Playground.Core.ViewModels;
using MvvmCross.Binding.BindingContext;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    [MvxTabPresentation(TabTitle = "Tab1")]
    public partial class Tab1View : MvxViewController<Tab1ViewModel>
    {
        public Tab1View(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = this.CreateBindingSet<Tab1View, Tab1ViewModel>();
            set.Bind(btnClose).To(vm => vm.CloseCommand);
            set.Apply();
        }
    }
}
