// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Mac.Views;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
    public partial class ToolbarWindow : MvxWindowController
	{
		public ToolbarWindow (IntPtr handle) : base (handle)
		{
		}
    }
}
