// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MvvmCross.Mac.Views;
using MvvmCross.Mac.Views.Presenters.Attributes;
using MvvmCross.Binding.BindingContext;
using Playground.Core.ViewModels;

namespace Playground.Mac
{
    [MvxFromStoryboard("Main")]
//    [MvxWindowPresentation(PositionX = 300)]
    [MvxWindowPresentation("ToolbarWindow", "Main")]
    public partial class WindowView : MvxViewController<WindowViewModel>
    {
        public WindowView(IntPtr handle) : base(handle)
        {
            Title = "Window view";
        }

        public ToolbarWindow WindowController {
            get { return View.Window != null ? (ToolbarWindow)View.Window.WindowController : null; }
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var set = this.CreateBindingSet<WindowView, WindowViewModel>();
            set.Bind(btnClose).To(vm => vm.CloseCommand);
            set.Apply();
        }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            var set = this.CreateBindingSet<WindowView, WindowViewModel>();
            set.Bind(WindowController.TextTitle).For(v => v.StringValue).To(vm => vm.Title);
            set.Apply();
        }
    }
}
