name: "Shared .NET Steps"
inputs:
  dotnet-version:
    description: 'The .NET version to install'
    required: false
    default: '9.0.304'
runs:
  using: "composite"
  steps:
    - name: Install .NET ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Install .NET workloads
      run: |
        dotnet --version
        dotnet workload install android ios tvos macos maccatalyst --version ${{ inputs.dotnet-version }}