<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>$(_MvxCommonTargets)</TargetFrameworks>
    <AssemblyName>MvvmCross.UnitTest.Common</AssemblyName>
    <RootNamespace>MvvmCross.UnitTest.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MvvmCross.Tests\MvvmCross.Tests.csproj" />
  </ItemGroup>

</Project>
