// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Playground.TvOS
{
	public partial class ChildView : UIViewController
	{
		public ChildView (IntPtr handle) : base (handle)
		{
		}
	}
}
