//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cirrious.Conference.UI.Droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxHttpSource = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int grey = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int icongrey = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int lightgrey = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int listseparator = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int mainText = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int white = 2130968581;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appbar_base = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int appbar_bus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int appbar_calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int appbar_camera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int appbar_city = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int appbar_database = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int appbar_email = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int appbar_favs = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int appbar_home = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int appbar_link = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int appbar_people = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int appbar_phone = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int appbar_questionmark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int appbar_twitter = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_pulltorefresh_arrow = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int list_selector = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int pull_to_refresh_header_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int SQLBitsLogo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int star_gold45 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int star_gold_selector = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int star_grey45 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int star_grey_selector = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Tab_Favorites = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Tab_Sessions = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Tab_Tweets = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Tab_Welcome = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int tweetShare = 2130837532;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int ContentTextView = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int FavoriteButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindableListItemTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int NameTextView = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int PeoplePanel = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int PeopleTextView = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int PersonImage = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int RoomPanel = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int RoomTextView = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int SessionList = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int SponsorImageView = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int SponsorList = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int TimeTextView = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int TitleTextView = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int TwitterImageView = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int map = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int pull_to_refresh_image = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int pull_to_refresh_layout = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int pull_to_refresh_progress = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int pull_to_refresh_text = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int pull_to_refresh_updated_at = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int refresh_lower_button = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int refresh_upper_button = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int starbutton = 2131034136;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChildPage_Sessions = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChildPage_Twitter = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChildPage_Welcome = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItem_SeparatorToString = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListItem_Session = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListItem_SessionTimeSlot = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem_Sponsor = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListItem_Tweet = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Page_About = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Page_Home = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Page_Map = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Page_Session = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Page_SessionList = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Page_SplashScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Page_Sponsors = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int pull_down_pull_to_refresh_list = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int pull_to_refresh_bindable_list = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int pull_up_pull_to_refresh_list = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SplashScreen = 2130903058;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int AboutPageBodyText = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int AboutPageTitle = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int IconButton = 2131165184;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
