nuget delete MvvmCross.PortableSupport 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.CrossCore 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Droid.Fragging 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Accelerometer 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.All 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Bookmarks 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Color 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.DownloadCache 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Email 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.FieldBinding 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.File 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Json 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.JsonLocalisation 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Location 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Messenger 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.MethodBinding 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Network 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.PhoneCall 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.PictureChooser 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.ReflectionEx 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.ResourceLoader 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Share 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.SoundEffects 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.SQLite 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.ThreadUtils 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.Visibility 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Plugin.WebBrowser 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.MvvmCrossLibraries 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.StarterPack 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Tests 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Touch.Dialog 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Droid.Dialog 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.BindingEx 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.AutoViews 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Touch.AutoViews 3.0.14-beta1  -NoPrompt
nuget delete MvvmCross.HotTuna.Droid.AutoViews 3.0.14-beta1  -NoPrompt
