nuget push MvvmCross.PortableSupport.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.CrossCore.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Droid.Fragging.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Droid.FullFragging.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Accelerometer.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.All.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Bookmarks.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Color.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.DownloadCache.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Email.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.FieldBinding.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.File.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Json.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.JsonLocalisation.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Location.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Messenger.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.MethodBinding.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Network.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.PhoneCall.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.PictureChooser.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.ReflectionEx.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.ResourceLoader.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Share.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.SoundEffects.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.SQLite.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.ThreadUtils.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.Visibility.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Plugin.WebBrowser.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.MvvmCrossLibraries.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.StarterPack.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Tests.3.2.2-beta1.nupkg
nuget push MvvmCross.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Touch.Dialog.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Droid.Dialog.3.2.2-beta1.nupkg
nuget push MvvmCross.BindingEx.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.AutoViews.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Touch.AutoViews.3.2.2-beta1.nupkg
nuget push MvvmCross.HotTuna.Droid.AutoViews.3.2.2-beta1.nupkg
