#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Tutorial.UI.Droid.Resource", IsApplication=true)]

namespace Tutorial.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int MvxDropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int MvxItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int MvxSource = 2130771972;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_pulltorefresh_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pull_to_refresh_header_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tab_speakers = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int tab_speakers_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tab_speakers_unselected = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000b
			public const int LoadingText = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int email_from = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int email_header = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int email_message = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int pull_to_refresh_image = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int pull_to_refresh_layout = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int pull_to_refresh_progress = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int pull_to_refresh_text = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int pull_to_refresh_updated_at = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int refresh_lower_button = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int refresh_upper_button = 2130968580;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem_Email = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem_ViewModel = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Page_CompositeView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page_Location = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page_MainMenuView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Page_PullToRefreshView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Page_SimpleTextPropertyView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Page_TipView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int pull_down_pull_to_refresh_list = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int pull_to_refresh_bindable_list = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int pull_to_refresh_list = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int pull_up_pull_to_refresh_list = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SplashScreen = 2130903052;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Loading = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxImageView = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
