//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManagement.Droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxHttpSource = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_mark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_save = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int MyButton = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int add_customer = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int change_customer = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int delete_customer = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int save_customer = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int text1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int text2 = 2130968579;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem_Customer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Page_CustomerListView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Page_DetailsCustomerView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Page_EditCustomerView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Splash = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int customer_edit_menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int customer_list_menu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int customer_menu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int customer_new_menu = 2131099651;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int menu_add_customer = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int menu_save_customer = 2131034115;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
