#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CustomerManagement.Droid.Resource", IsApplication=true)]

namespace CustomerManagement.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int MvxDropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int MvxItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int MvxSource = 2130771972;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_mark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_save = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int spinner_default_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int spinner_default_holo_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040014
			public const int MyButton = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int add_customer = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int change_customer = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int delete_customer = 2130968600;
			
			// aapt resource value: 0x7f040005
			public const int dialog_BoolField = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int dialog_Button = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int dialog_DisclosureField = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int dialog_HtmlField = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int dialog_ImageLeft = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int dialog_ImageRight = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int dialog_LabelField = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int dialog_LabelPercentageField = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int dialog_LabelSubtextField = 2130968578;
			
			// aapt resource value: 0x7f04000c
			public const int dialog_Panel = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int dialog_RadioButtonList = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int dialog_SliderField = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int dialog_Spinner = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int dialog_ValueField = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int iFormFieldValue = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int listitempart_subtitle = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int listitempart_title = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int save_customer = 2130968597;
			
			// aapt resource value: 0x7f040010
			public const int text1 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int text2 = 2130968593;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_html = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labeldisclosure = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labelfieldbelow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_labelfieldright = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_multiline_labelfieldbelow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_onofffieldright = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_panel = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_root = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_selectlist = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_selectlistfield = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_textarea = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textfieldbelow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_textfieldright = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ListItem_Customer = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int listitem_TitleAndSubTitle = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Main = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Page_CustomerListView = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Page_DetailsCustomerView = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Page_EditCustomerView = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Splash = 2130903068;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int customer_edit_menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int customer_list_menu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int customer_menu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int customer_new_menu = 2131099651;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int menu_add_customer = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int menu_save_customer = 2131034115;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxImageView = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
