name: "Shared Steps"
description: Shared steps for .NET and Java setup
inputs:
  dotnet-version:
    description: 'The .NET version to install'
    required: false
    default: '10.0.100'
  dotnet-workload-version:
    description: 'The .NET workload version to install'
    required: false
    default: '10.0.100'
  java-version:
    description: 'The Java version to install'
    required: false
    default: '21'
  java-distribution:
    description: 'The Java distribution to install'
    required: false
    default: 'temurin'
runs:
  using: "composite"
  steps:
    - name: Install .NET ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore .NET tools
      shell: pwsh
      run: dotnet tool restore

    - name: Install .NET workloads
      shell: pwsh
      run: |
        dotnet --version
        dotnet workload install android ios tvos macos maccatalyst --version ${{ inputs.dotnet-workload-version }}

    - name: Set up JDK
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}