name: Build

on:
  pull_request:
    branches: 
      - main
      - develop

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: 17
  NET_VERSION: 9.0.302

jobs:
  build:
    permissions:
      id-token: write
      attestations: write

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Install .NET ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: ${{ env.NET_VERSION }}

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Install .NET workloads
      run: |
        dotnet --version
        dotnet workload install android ios tvos macos maccatalyst --version ${{ env.NET_VERSION }}

    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 #v4.7.0
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build
      run: dotnet run --project build/Build.csproj -- --verbosity=Minimal --artifactsDir="${{ github.workspace }}\output"

    - name: Upload artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: build-artifacts
        path: output
