name: Build

on:
  pull_request:
    branches: 
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      pull-requests: write

    runs-on: windows-latest
    
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
        fetch-tags: true  

    - uses: ./.github/actions/shared

    - name: Build
      run: dotnet run --project build/Build.csproj -- --verbosity=Minimal --artifactsDir="${{ github.workspace }}\output" --ctrfDir="${{ github.workspace }}\ctrf"

    - name: Print ctrf files in output
      run: |
        echo "ctrf files in output:"
        dir ${{ github.workspace }}\ctrf
    
    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@9bd31188517cfb3ff683f135041cc3bfbb0c78b3 # v1.0.25
      with:
        report-path: ${{ github.workspace }}/ctrf/*.ctrf.json
        summary-report: true
        github-report: true
        pull-request: true
        update-comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()

    - name: Upload artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: build-artifacts
        path: ${{ github.workspace }}\output
