name: Build

on:
  pull_request:
    branches: 
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      pull-requests: write

    runs-on: windows-latest
    
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        fetch-tags: true  

    - uses: ./.github/actions/shared

    - name: Build
      run: dotnet run --project build/Build.csproj -- --verbosity=Minimal --artifactsDir="${{ github.workspace }}\output" --ctrfDir="${{ github.workspace }}\ctrf"

    - name: Print ctrf files in output
      run: |
        echo "ctrf files in output:"
        dir ${{ github.workspace }}\ctrf
    
    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@0f299074936c32ccaab5be5230511f6b2b9080aa # v1.0.28
      with:
        report-path: ${{ github.workspace }}/ctrf/*.ctrf.json
        summary-report: true
        github-report: true
        pull-request: true
        update-comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()

    - name: Upload artifacts
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: build-artifacts
        path: ${{ github.workspace }}\output
