name: Build

on:
  pull_request:
    branches: 
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      pull-requests: write

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
        fetch-tags: true  

    - uses: ./.github/actions/shared

    - name: Build
      run: dotnet run --project build/Build.csproj -- --verbosity=Minimal --artifactsDir="${{ github.workspace }}\output" --ctrfDir="${{ github.workspace }}\ctrf"

    - name: Print ctrf files in output
      run: |
        echo "ctrf files in output:"
        dir ${{ github.workspace }}\ctrf
    
    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@646f98cfc16c6f7a0e1f6100cabe2deb95dd2eef #v1.0.22
      with:
        report-path: ${{ github.workspace }}/ctrf/*.ctrf.json
        summary-report: true
        github-report: true
        pull-request: true
        update-comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()

    - name: Upload artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
      with:
        name: build-artifacts
        path: ${{ github.workspace }}\output
