name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
        fetch-tags: true  

    - name: Install .NET 10.0.300
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 10.0.300

    - name: Restore .NET tools
      shell: pwsh
      run: dotnet tool restore

    - name: Add the local .NET to the envvars (PATH, DOTNET_ROOT)
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_PATH"
        echo "DOTNET_ROOT=$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_ENV"
        echo "DOTNET_INSTALL_DIR=$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_ENV"
        echo "DOTNET_SYSTEM_NET_SECURITY_NOREVOCATIONCHECKBYDEFAULT=true" >> "$GITHUB_ENV"

    - name: Ensure we are using the correct .NET
      shell: pwsh
      run: |
        dotnet --version
        dotnet --info
        dotnet workload --info

    - name: Install .NET workloads
      shell: pwsh
      run: dotnet workload install android

    - name: Reset tracked files to clean workspace
      shell: bash
      run: |
        git reset --hard HEAD