name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        fetch-tags: true  

    - name: Install .NET 10.0.100
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: 10.0.100

    - name: Restore .NET tools
      shell: pwsh
      run: dotnet tool restore

    - name: Add the local .NET to the envvars (PATH, DOTNET_ROOT)
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_PATH"
        echo "DOTNET_ROOT=$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_ENV"
        echo "DOTNET_INSTALL_DIR=$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_ENV"
        echo "DOTNET_SYSTEM_NET_SECURITY_NOREVOCATIONCHECKBYDEFAULT=true" >> "$GITHUB_ENV"

    - name: Ensure we are using the correct .NET
      shell: pwsh
      run: |
        dotnet --version
        dotnet --info
        dotnet workload --info

    - name: Install .NET workloads
      shell: pwsh
      run: dotnet workload install android

    - name: Reset tracked files to clean workspace
      shell: bash
      run: |
        git reset --hard HEAD