name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0
        fetch-tags: true  

    - name: Install .NET 10.0.100
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: 10.0.100

    - name: Restore .NET tools
      shell: pwsh
      run: dotnet tool restore

    - name: Add the local .NET to the envvars (PATH, DOTNET_ROOT)
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_PATH"
        echo "DOTNET_ROOT=$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_ENV"
        echo "DOTNET_INSTALL_DIR=$GITHUB_WORKSPACE/.dotnet" >> "$GITHUB_ENV"
        echo "DOTNET_SYSTEM_NET_SECURITY_NOREVOCATIONCHECKBYDEFAULT=true" >> "$GITHUB_ENV"

    - name: Ensure we are using the correct .NET
      shell: pwsh
      run: |
        dotnet --version
        dotnet --info
        dotnet workload --info

    - name: Install .NET workloads
      shell: pwsh
      run: dotnet workload install android

    - name: Reset tracked files to clean workspace
      shell: bash
      run: |
        git reset --hard HEAD