name: dotnet format

on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: ./.github/actions/shared

    - name: Run dotnet format
      run: |
        dotnet format whitespace --no-restore --verify-no-changes MvvmCross.slnx
