name: dotnet format

on: [pull_request]

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - uses: ./.github/actions/shared

    - name: Run dotnet format
      run: |
        dotnet format whitespace --no-restore --verify-no-changes MvvmCross.slnx
