name: dotnet format

on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: ./.github/actions/shared

    - name: Run dotnet format
      run: |
        dotnet format whitespace --no-restore --verify-no-changes MvvmCross.slnx
