name: Release

on:
  push:
    branches: 
      - develop
      - main
      - release/**
      - hotfix/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
      attestations: write

    runs-on: windows-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: audit
  
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: ./.github/actions/shared

    - name: Build
      run: dotnet run --project build/Build.csproj -- --verbosity=Minimal --artifactsDir="${{ github.workspace }}\output"

    - name: Install sign tool
      run: dotnet tool install --tool-path . sign --version 0.9.1-beta.25379.1

    - name: 'Az CLI login'
      uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
      with:
        client-id: ${{ secrets.SIGN_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.SIGN_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.SIGN_AZURE_SUBSCRIPTION_ID }}

    - name: Sign artifacts
      shell: pwsh
      run: >
        ./sign code azure-key-vault
        **/*.nupkg
        --base-directory "${{ github.workspace }}/output"
        --publisher-name "MvvmCross"
        --description "MvvmCross is a cross platform MVVM framework"
        --description-url "https://mvvmcross.com"
        --azure-key-vault-url "${{ secrets.SIGN_AZURE_VAULT_URL }}"
        --azure-key-vault-certificate "${{ secrets.SIGN_AZURE_KEY_VAULT_CERTIFICATE_ID }}"

    - name: Attest NuGet packages
      uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
      with:
        subject-path: ${{ github.workspace }}\output\NuGet\*.nupkg
        sbom-path: ${{ github.workspace }}\output\sbom\MvvmCross.sbom.json
        push-to-registry: true

    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: build-artifacts
        path: ${{ github.workspace }}\output

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: NuGet Push
      env:
        NUGET_AUTH_TOKEN: ${{ steps.login.outputs.NUGET_API_KEY }}
        SOURCE_URL: https://api.nuget.org/v3/index.json
      run: |
        dotnet nuget push -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} ${{ github.workspace }}\output\**\*.nupkg

    - name: GitHub Packages Push
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_API_KEY }}
        SOURCE_URL: https://nuget.pkg.github.com/mvvmcross/index.json
      run: |
        dotnet nuget push -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} ${{ github.workspace }}\output\**\*.nupkg           
