name: Sonar

on:
  push:
    branches: 
    - develop
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

env:
  verbosity: 'minimal'
  sonarKey: 'MvvmCross_MvvmCross'
  sonarOrg: 'mvx'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
        fetch-tags: true  

    - uses: ./.github/actions/shared

    - name: Build
      run: dotnet run --project build/Build.csproj -- --verbosity=${{ env.verbosity }} --target=Sonar --sonarToken=${{ secrets.SONAR_TOKEN }} --sonarKey=${{ env.sonarKey }} --sonarOrg=${{ env.sonarOrg }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
