name: Sonar

on:
  push:
    branches: 
    - develop
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

env:
  verbosity: 'minimal'
  sonarKey: 'MvvmCross_MvvmCross'
  sonarOrg: 'mvx'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        fetch-depth: 0
        fetch-tags: true  

    - uses: ./.github/actions/shared

    - name: Build
      run: dotnet run --project build/Build.csproj -- --verbosity=${{ env.verbosity }} --target=Sonar --sonarToken=${{ secrets.SONAR_TOKEN }} --sonarKey=${{ env.sonarKey }} --sonarOrg=${{ env.sonarOrg }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
